# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moves.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmoves.proto\"\x9b\x01\n\x04Move\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0b\n\x03ply\x18\x02 \x01(\x05\x12\x0c\n\x04move\x18\x03 \x01(\x05\x12\x0b\n\x03san\x18\x04 \x01(\t\x12\x0b\n\x03uci\x18\x05 \x01(\t\x12\r\n\x05\x63lock\x18\x06 \x01(\x02\x12\x0c\n\x04\x65val\x18\x07 \x01(\t\x12\x0b\n\x03\x66\x65n\x18\x08 \x01(\t\x12\x14\n\x0cshredder_fen\x18\t \x01(\t\x12\r\n\x05\x63olor\x18\n \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moves_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVE._serialized_start=16
  _MOVE._serialized_end=171
# @@protoc_insertion_point(module_scope)
